title: Infinityheroes Documentation
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs
source: docs

url: https://just-the-docs.github.io

aux_links:
  Website: https://ifheroes.de
